name: Simulink CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Run buildtool
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2026a
          products: >
            MATLAB
            Simulink
            MATLAB_Coder
            Simulink_Coder

      - name: Run default build task
        uses: matlab-actions/run-build@v2
